Repository cert-manager/aws-privateca-issuer, pull requests merged in 2021-11, with the labels that each got.

#68 Add end-to-end test written in Go
  .gitignore
  Dockerfile
  Makefile
  README.md
  config/samples/awspcaclusterissuer_ec/_v1beta1_awspcaclusterissuer_ec.yaml
  config/samples/awspcaclusterissuer_rsa/_v1beta1_awspcaclusterissuer_rsa.yaml
  config/samples/awspcaissuer_ec/_v1beta1_awspcaissuer_ec.yaml
  config/samples/awspcaissuer_rsa/_v1beta1_awspcaissuer_rsa.yaml
  e2e/aws_helpers.go
  e2e/e2e_test.go
  e2e/k8_helpers.go
  e2e/kind_config/config.yaml
  e2e/kind_config/install_eks.yaml
  e2e/kind_config/registry_configmap.yaml
  e2e/kind_config/unauth_role.yaml
  go.mod
  go.sum
  pkg/api/v1beta1/awspcaissuer_types.go
  pkg/clientset/v1beta1/api.go
  pkg/clientset/v1beta1/issuers.go
  pkg/clientset/v1beta1/register.go
  test_utils/create_ca.sh
  test_utils/delete_ca.sh
  test_utils/e2e_test.sh
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#52 Added plug-in release number to user-agent
  Dockerfile
  Makefile
  pkg/api/config/injection_targets.go
  pkg/api/injections/injection_targets.go
  pkg/api/v1beta1/groupversion_info.go
  pkg/aws/pca.go
  pkg/controllers/certificaterequest_controller.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#66 Add resource limits to kube-rbac-proxy container
  config/default/manager_auth_proxy_patch.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#73 Added post-release Helm test
  Makefile
  e2e/helm_test.sh
Labels: dco-signoff: yes, size/L, lgtm, approved

#65 Add GitHub action to sync README and CRDs
  .github/workflows/sync.yml
Labels: dco-signoff: yes, size/L, lgtm, approved

#70 Fixed a casting issue where a validity duration under 24h would cause…
  e2e/e2e_test.go
  pkg/aws/pca.go
Labels: dco-signoff: yes, size/S, lgtm, approved

#77 Add signoff to automated CRD sync commit
  .github/workflows/sync.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#79 Add signoff to README sync commit
  .github/workflows/sync.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#75 Added known validity duration issue to README
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved

#81 Add clarity to README around setting up e2e testing
  README.md
Labels: dco-signoff: yes, size/S, lgtm, approved

#80 Update the version and appVersion to 1.0.0
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#82 Added environment variables to helm chart, as well as updated Makefil…
  Makefile
  charts/aws-pca-issuer/templates/deployment.yaml
  charts/aws-pca-issuer/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#83 Update sync.yml
  .github/workflows/sync.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#84 Update README to include information about Cert-Manager UsageType tra…
  README.md
Labels: dco-signoff: yes, size/M, lgtm, approved

#85 Add new CI/CD + testing with Github Actions
  .github/workflows/ci.yml
  .github/workflows/on-push-to-main-branch.yml
  .github/workflows/on-release.yml
  .github/workflows/on-safe-to-test-label.yml
  .github/workflows/release.yml
  Makefile
  README.md
  e2e/k8_helpers.go
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/certificaterequest_controller_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved, safe to test

#86 Update Helm Chart on release
  .github/workflows/on-release.yml
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test

#87 Update Helm chart to point to new ECR
  .github/workflows/on-safe-to-test-label.yml
  charts/aws-pca-issuer/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test

#88 Fix helm release workflow with CR_PAT
  .github/workflows/on-release.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#89 Add back removed v0.3.1 chart, automatically deleted by helm chart gh…
  index.yaml
Labels: dco-signoff: yes, size/S

#91 Update README to remove known issues as they are fixed in the lastest…
  README.md
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test

#94 Change BlankEndEntityCertificate_CSRPassthrough -> BlankEndEntityCert…
  pkg/aws/pca.go
  pkg/aws/pca_test.go
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#95 Added user-agent injection to github actions so version number will a…
  .github/workflows/on-push-to-main-branch.yml
  .github/workflows/on-release.yml
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test
