Repository cert-manager/aws-privateca-issuer, pull requests merged in 2021-06, with the labels that each got.

#27 Move repository to the cert-manager org
  Dockerfile
  PROJECT
  README.md
  charts/aws-pca-issuer/Chart.yaml
  charts/aws-pca-issuer/templates/_helpers.tpl
  charts/aws-pca-issuer/templates/deployment.yaml
  charts/aws-pca-issuer/templates/hpa.yaml
  charts/aws-pca-issuer/templates/rbac.yaml
  charts/aws-pca-issuer/templates/service-monitor.yaml
  charts/aws-pca-issuer/templates/service.yaml
  config/default/kustomization.yaml
  go.mod
  main.go
  pkg/controllers/awspcaclusterissuer_controller.go
  pkg/controllers/awspcaissuer_controller.go
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/certificaterequest_controller_test.go
  pkg/controllers/genericissuer_controller.go
  pkg/controllers/genericissuer_controller_test.go
  pkg/util/issuers.go
Labels: dco-signoff: yes, size/L

#28 Update version badge to new URL
  OWNERS
  README.md
Labels: dco-signoff: yes, size/S

#31 Use a md5 sum for idempotency token
  pkg/aws/pca.go
  pkg/aws/pca_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#34 troubleshooting notes added
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
