Repository cert-manager/aws-privateca-issuer, pull requests merged in 2021-07, with the labels that each got.

#29 Add support for certificate usages with templateARN
  pkg/aws/pca.go
  pkg/aws/pca_test.go
Labels: approved, dco-signoff: yes, enhancement, lgtm, size/L

#35 Use the PrivateCA's Signature Algorithm as the Signature Algorithm in…
  .gitignore
  Dockerfile
  Makefile
  README.md
  config/manager/kustomization.yaml
  config/samples/awspcaclusterissuer_ec/rsa_certificate_awspcaclusterissuer.yaml
  config/samples/awspcaclusterissuer_rsa/ec_certificate_awspcaclusterissuer.yaml
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/genericissuer_controller.go
  pkg/util/issuers.go
  test_utils/create_ca.sh
  test_utils/e2e_test.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#36 Pass user agent, including version info string
  pkg/aws/pca.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#38 Fix helm chart link in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#41 Changed how the aws config is created to be inline with aws documenta…
  go.mod
  go.sum
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/genericissuer_controller.go
Labels: approved, dco-signoff: yes, lgtm, size/XL
