Repository cert-manager/aws-privateca-issuer, pull requests merged in 2021-12, with the labels that each got.

#99 Update README to mention IRSA
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#97 Removed dropdown and add text area for version in issues template
  .github/ISSUE_TEMPLATE/bug-report.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#55 feat: adding cert template for sub ca creation
  e2e/aws_helpers.go
  e2e/e2e_test.go
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller.go
Labels: dco-signoff: yes, size/L, lgtm, approved, safe to test

#101 Changes for release v1.1.0
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#104 Fix Readme spacing
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#106 Added install-latest Makefile target to allow testing of ecr image
  Makefile
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test
