Repository cert-manager/aws-privateca-issuer, pull requests merged in 2022-02, with the labels that each got.

#111 overridden durations should be specified from epoch
  pkg/aws/pca.go
  pkg/aws/pca_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved, safe to test

#110 Test with cert-manager 1.7
  Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#120 Added blog-test to GitHub workflow
  .github/workflows/on-safe-to-test-label.yml
  e2e/blog-test/nlb-tls-app.yaml
  e2e/blog_test.sh
Labels: dco-signoff: yes, size/S

#124 Updated go version to 1.17.7
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes, size/S

#127 Updated supported golang version to 1.17+
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#130 Removed testLog
  pkg/aws/pca_test.go
Labels: dco-signoff: yes

#125 Updated go version to 1.17.7 (#124)
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test

#134 Testing fix
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes, size/S, lgtm, approved, safe to test

#123 Update logr dependency (#122)
  Dockerfile
  go.mod
  go.sum
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller_test.go
  pkg/controllers/genericissuer_controller_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XXL, safe to test

#136 Removed if statements to test workflow
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes

#139 Added if condition to run jobs with workflow dispatch
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#137 Prepare for dependabot
  .github/dependabot.yml
  .github/workflows/on-safe-to-test-label.yml
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, size/XXL

#138 Added blog-test to GitHub workflow
  .github/workflows/on-safe-to-test-label.yml
  e2e/blog-test/nlb-tls-app.yaml
  e2e/blog_test.sh
Labels: dco-signoff: yes, size/S, lgtm, approved
