Repository cert-manager/aws-privateca-issuer, pull requests merged in 2024-06, with the labels that each got.

#323 Update Go to 1.22.3
  .github/workflows/on-safe-to-test-label.yml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#327 Add ARM testing
  .github/workflows/on-safe-to-test-label.yml
  .github/workflows/test-plugin.yml
Labels: dco-signoff: yes, size/M, lgtm, approved

#319 feat: linux/arm64 compatibility
  .github/workflows/on-push-to-main-branch.yml
  .github/workflows/on-release.yml
  Dockerfile
  Makefile
Labels: dco-signoff: yes, size/S, lgtm, approved
