Repository cert-manager/aws-privateca-issuer, pull requests merged in 2024-09, with the labels that each got.

#337 Update README.md
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved

#338 Update controller to issue certs asynchronously
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/certificaterequest_controller_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#336 feat: Support disabling Kubernetes client side rate limiting
  Makefile
  README.md
  charts/aws-pca-issuer/templates/deployment.yaml
  charts/aws-pca-issuer/values.yaml
  e2e/kind_config/config.yaml
  main.go
Labels: dco-signoff: yes, size/M, lgtm, approved
