Repository cert-manager/aws-privateca-issuer, pull requests merged in 2024-10, with the labels that each got.

#340 use sha256 sum for idempotency token
  pkg/aws/pca.go
  pkg/aws/pca_test.go
Labels: dco-signoff: yes, size/S, lgtm, approved

#341 Run tests with cert-manager 1.16.0
  Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#343 Update blog test
  Makefile
  e2e/blog_test.sh
  e2e/kind_config/install_eks.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#345 Update chart version to 1.4.0
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, chart update
