Repository cert-manager/aws-privateca-issuer, pull requests merged in 2025-04, with the labels that each got.

#377 Use IMDSv2
  e2e/blog_test.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#360 Update timeout in blog test
  e2e/blog_test.sh
  e2e/helm_test.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#383 Sync CRDs between config/crd/bases and charts/aws-pca-issuer/crds
  charts/aws-pca-issuer/crds/awspca.cert-manager.io_awspcaclusterissuers.yaml
  charts/aws-pca-issuer/crds/awspca.cert-manager.io_awspcaissuers.yaml
Labels: dco-signoff: yes, size/M, lgtm, approved

#386 Add end-to-end tests for the KeySelector options
  e2e/e2e_test.go
Labels: dco-signoff: yes, size/M, lgtm, approved

#384 Update certificate to Pending instead of Failed when issuer is not ready
  .gitignore
  e2e/e2e_test.go
  e2e/k8_helpers.go
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/certificaterequest_controller.go
  pkg/controllers/certificaterequest_controller_test.go
  pkg/controllers/genericissuer_controller.go
  pkg/controllers/genericissuer_controller_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#385 Improve end-to-end test time
  .github/workflows/on-safe-to-test-label.yml
  .github/workflows/test-plugin.yml
  Dockerfile
  Makefile
Labels: dco-signoff: yes, size/S, lgtm, approved

#379 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, size/S, lgtm, approved

#387 Add defaults for Docker build-args
  Dockerfile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#393 Set the user-agent based on the destination repo of the built image
  .github/workflows/on-release.yml
  Dockerfile
  Makefile
  pkg/api/injections/injection_targets.go
  pkg/aws/pca.go
Labels: dco-signoff: yes, size/S, lgtm, approved

#390 Update charts/aws-pca-issuer/README.md using `make helm-docs`
  .github/workflows/sync-helm-readme.yml
  .github/workflows/sync.yml
  Makefile
  SECURITY_CONTACTS
  charts/aws-pca-issuer/README.md
  charts/aws-pca-issuer/values.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#396 Update chart version to v1.5.0
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, chart update
