Repository cert-manager/aws-privateca-issuer, pull requests merged in 2025-05, with the labels that each got.

#399 Update templates in README to reflect templates used in code
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved, safe to test

#398 Replace external github action dependencies
  .github/workflows/on-release.yml
  .github/workflows/on-safe-to-test-label.yml
  .github/workflows/sync-helm-readme.yml
  .github/workflows/sync.yml
  .github/workflows/test-plugin.yml
Labels: dco-signoff: yes, size/S, lgtm, approved

#401 Add node affinity
  charts/aws-pca-issuer/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#402 Update chart version to v1.6.0
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, chart update

#406 Revert "Update chart version to v1.6.0"
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#404 Refresh the cached client when the issuer is updated
  pkg/aws/pca.go
  pkg/aws/pca_test.go
  pkg/controllers/genericissuer_controller.go
Labels: dco-signoff: yes, size/S, lgtm, approved

#408 Add wait for IAM AccessKey propagation delay
  e2e/e2e_test.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#407 Reapply "Update chart version to v1.6.0"
  charts/aws-pca-issuer/Chart.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, chart update
